### ISSUE TITLE
Publish the app upon signup (i.e. no need to complete profile)

### ISSUE THREAD

**Issue by engramar** [codesydney/classified-ads-app-for-good#147]
Make the below the default values after a successful sign up to publish app. 

- isProfileComplete:true
- Default profile pic below
https://ustaa.s3.ap-southeast-2.amazonaws.com/images/USTAA-Profile.png

USTAA will just send a reminder to those with incomplete profiles to finish their profile completion.

**Comment by promie** [comment]
@engramar For this update, I've excluded the `isProfileComplete` from the search criteria. We probably shouldn't set isProfileComplete to true by default just to ensure profiles show up in searches, as it could interfere with the logic for updating profiles. It seems simplest to comment out this criteria for now, and we can always reintroduce it if needed later. We need to maintain the accurate state of isProfileComplete so we can identify and possibly follow up with users who haven't completed their profiles.
