### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by engramar** [codesydney/classified-ads-app-for-good#3]
As simple as possible, just a search box in the middle and the usual menu tab and footer
https://www.figma.com/file/DyT6QcKPcTSnDlm4tKMhWW/USTAA-Directory?type=design&node-id=0-1&mode=design&t=efGVdckoOOUaVRqa-0
![image](https://github.com/codesydney/cs-directory/assets/7553347/51ab088f-51b0-4ae1-a832-4c8f52b4e3b1)

**Comment by engramar** [comment]
Hi @nathanksou , I just realised that this is already covered in your Smart Search ticket so just assigning it to you. Cheers mate.

**Comment by nathanksou** [comment]
Adding a small acceptance criteria here:
- When I search from the home page, Then I should see the results on the /search route

**Comment by engramar** [comment]
Covered in Issue #21
