### ISSUE TITLE
Alumni Profile Edit Page

### ISSUE THREAD

**Issue by engramar** [codesydney/classified-ads-app-for-good#7]
Once logged in, user profile is displayed (like a LinkedIn profile with profile pic and all) and all editable. See anticipated initial form fields below. 

Personal
- Firstname (+)
- Lastname (+)
- Email
- Phone
- State (+)
- Suburb 
- Postcode
- Quick story about Australian immigration
- Profile Pic (+)

Education
- College (+)
- Course (+)
- Year Graduated (+)

Services
- Services Logo (+)
- Services URL (+)

Admin 
- Reset Password
- Edit Profile

Membership Fee
- Link to membership fee payment -> https://buy.stripe.com/28o9CgfO917C51e28a

Consent
- Consent clause 'By providing your personal information, you consent to its use for the purpose of USTAA including publishing non-personally identifiable information on USTAA's social media pages'.

**Comment by engramar** [comment]
https://www.figma.com/file/DyT6QcKPcTSnDlm4tKMhWW/USTAA-Directory?type=design&node-id=0-1&mode=design&t=efGVdckoOOUaVRqa-0

![image](https://github.com/codesydney/cs-directory/assets/7553347/eb95faef-4b54-4a3d-bc1c-19afcb2e9a5c)

**Comment by nathanksou** [comment]
Adding this Acceptance Criteria:
- When I click on an available search result, Then I should see information pertaining to the user of that result

**Comment by promie** [comment]
@brodiehunt The API to update users profile has been done in this PR:

https://github.com/codesydney/classified-ads-app-for-good/pull/78
