### ISSUE TITLE
Backend: Only show user in search results if they've filled in mandatory fields

### ISSUE THREAD

**Issue by promie** [codesydney/classified-ads-app-for-good#87]
@engramar could you please help define which fields a user needs to update before the profile can appear in the search results? The current behaviour is that all users right now appear on the search list. Should we filter only those with complete profile?

Cc: @brodiehunt

**Comment by engramar** [comment]
Morning @promie, Sounds like a good idea. We can set mandatory fields during profile update, and only display those ones populated. So a newly signed up user will not have their profile published as yet until they fill out all the mandatory fields as shown below. 

(+) - displayed publicly 
(#) - mandatory field

**Personal**
Firstname (+)(#)
Lastname (+)(#)
Email (#)
Phone 
State (+)(#)
Suburb
Postcode (#)
Quick story about Australian immigration (#)
Profile Pic (+)(#)

**Education**
College (+)(#)
Course (+)(#)
Year Graduated (+)(#)

**Services**
Services Logo (+)
Services URL (+)
Admin

**Membership**
Membership Fee
Link to membership fee payment -> https://buy.stripe.com/28o9CgfO917C51e28a

**Settings**
Reset Password
Edit Profile

**Consent**
Consent clause 'By providing your personal information, you consent to its use for the purpose of USTAA including publishing non-personally identifiable information on USTAA's social media pages'.
