### ISSUE TITLE
Detailed view of each Alumnus/Alumna

### ISSUE THREAD

**Issue by engramar** [codesydney/classified-ads-app-for-good#98]
Link to work in progress -> https://classifieds.code.sydney/

When clicking 'View Profile' button of the chosen alumnus/alumna card during search, we should display some extra details on a separate page. As a start, just display the same information as what is shown on the card. 

Below are the data to be exposed on each detailed page. Notice that it is the same exposed fields on the search result card. Only addition is their story about Australian immigration. 

Note: (+) will be exposed publicly.

**Personal**
Firstname (+)
Lastname (+)
Email
Phone
State (+)
Suburb
Postcode
**_**Quick story about Australian immigration (+)**_**
Profile Pic (+)

**Education**
College (+)
Course (+)
Year Graduated (+)

**Services**
Services Logo (+)
Services URL (+)
Service Description (+)

**Comment by washington-shoji** [comment]
Hi @engramar this is just a WIP UI for the public user profile, I'm basing the UI on the search card for consitency. 
Please have a look at the images below and let me know how you folks feel about it. I think it has the info as per the AQ, but I'm happy to add/remove any other info you guys think is necessary. Please note, I'm using a in memory data mock but the feature should work with the remote/repo implementation.

![user-profile-info-desktop](https://github.com/codesydney/classified-ads-app-for-good/assets/60167200/66a2e1c9-afc0-49d2-8923-aaa39907085c)

![user-profile-info-mobile-1](https://github.com/codesydney/classified-ads-app-for-good/assets/60167200/db795df9-dcc7-4f00-99bb-19f300f86138)
![user-profile-info-mobile-2](https://github.com/codesydney/classified-ads-app-for-good/assets/60167200/f74c864c-e456-42b3-9667-0b0da0384e0b)

**Comment by engramar** [comment]
Perfect @washington-shoji! Thanks!
